rubber_cucumbers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todolist/', include('todolist.urls'))
]

todolist/urls.py
from django.conf.urls import url

from . import views

app_name = 'todolist'
urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^(?P<project_id>[0-9]+)/$', views.part_of_project, name='part_of_project'),
  url(r'^part/(?P<part_id>[0-9]+)/$', views.programm_of_part, name='programm_of_part'),
  ]

todolist/models.py
from django.db import models

class Project(models.Model):
  title = models.CharField(max_length=200)
  path_to_folder = models.CharField(max_length=200)
  date_created = models.DateTimeField('date created')

  def __str__(self):
    return self.title

class Part(models.Model):
  project = models.ForeignKey(Project, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  priority = models.IntegerField(default=10)
  status = models.CharField(max_length=20, default='Не активен')
  date_created = models.DateTimeField('date created')

  def __str__(self):
    return self.title

class Programm(models.Model):
  part = models.ForeignKey(Part, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  type = models.CharField(max_length=100)
  path_to_folder = models.CharField(max_length=300)
  date_created = models.DateTimeField('date created')

  def __str__(self):
    return self.title

todolist/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.db.models import F

from .models import Project, Part, Programm

def index(request):
  project_list = Project.objects.all()
  return render(request, 'todolist/index.html', {'project_list': project_list})


def part_of_project(request, project_id):
  part_list = Part.objects.filter(project=project_id)
  project = Project.objects.get(pk=project_id)
  return render(request, 'todolist/part.html', {'part_list': part_list, 'project': project})

def programm_of_part(request, part_id):
  programm_list = Programm.objects.filter(part=part_id)
  part = Part.objects.get(pk=part_id)
  project = Project.objects.get(pk=part.project.id)
  return render(request, 'todolist/programm.html', {'programm_list': programm_list, 'part': part, 'project': project}) 

todolist/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Rubber cucumbers{% endblock %}</title>
    {% load staticfiles %}
      <link rel="stylesheet" type="text/css" href="{% static 'todolist/style.css' %}" />
      <link rel="stylesheet" media="screen" href="{% static 'todolist/css/bootstrap.min.css' %}">
      <script src="{% static 'todolist/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <div id="content">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

todolist/templates/todolist/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container theme-showcase" role="main">
    <h1>Список проектов</h1> 
  
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Название проекта</th>
          <th>Статус производства</th>
      </thead>
      {% if project_list %}
        <tbody>
        {% for project in project_list %}
          <tr>
            <td><a href="{% url 'todolist:part_of_project' project.id  %}">{{ project.title }}</a></td>
            <td>
              <span class="label label-default">{{project.id}}</span>
              <span class="label label-info">{{project.id}}</span>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      {% else %}
        <p>Проектов не найдено.</p>
      {% endif %}
    </table>
  </div>
{% endblock content %}

todolist/templates/todolist/part.html
{% extends "base.html" %}

{% block content %}

  <div class="container theme-showcase" role="main">
    <h1>Название проекта: {{project.title}}</h1>
    <h3>Список деталей для этого проекта:</h3>
  
    {% if part_list %}
      <ul>
        {% for part in part_list %}
          <li><a href="{% url 'todolist:programm_of_part' part.id  %}">{{ part.title }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Деталей не найдено.</p>
    {% endif %}
  </div>

{% endblock content %}

todolist/templates/todolist/parts.html
{% if part_list %}
    <ul>
    {% for part in part_list %}
        <li><a href>{{ part.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No project are available.</p>
{% endif %}

todolist/templates/todolist/programm.html
{% extends "base.html" %}

{% block content %}
  <div class="container theme-showcase" role="main">
    <h1>Название проекта: {{project.title}}</h1>
    <h2>Название детали: {{part.title}}</h2>
    <h3>Список программ для этой детали:</h3>
  
    {% if programm_list %}
      <ul>
        {% for programm in programm_list %}
          <li><a href="/">{{ programm.title }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Программ не найдено.</p>
    {% endif %}
  </div>
{%endblock content%}